### ISSUE TITLE
is it ignoring silently the config file?

### ISSUE THREAD

**Issue by danielzzz** [mathiasHillmann/php-ide#4]
hi, thanks for this extension.

I have been trying it as a replacement for https://github.com/fterrag/vscode-php-cs-fixer
but it looks like the custom config file is being ignored or it behaves differently to the other extension.

namely, it seems to ignore:

```
'binary_operator_spaces' => [
            'align_double_arrow' => true,
            'align_equals'       => true,
        ],
        
```

is it a way to confirm the config file is being loaded?

thanks, dan

**Comment by mathiasHillmann** [comment]
This extension uses the latest version of PHP-CS-Fixer (Currently 3.3.2) while that extension used version 2.15.8.

There has been some changes to the config file and I highly recommend checking out the [upgrade guide](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/UPGRADE-v3.md) from 2.x to 3.x.

In the upgrade guide it specifies that the configuration `binary_operator_spaces` was dropped and the current alternative is `operators`. [There is more info in this section of the documentation.](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/operator/binary_operator_spaces.rst)

Please do leave a comment if the issue persists even with the new configuration values.

**Comment by mathiasHillmann** [comment]
I am closing the issue due to the original poster not posting again in over a week.
